// SPDX-License-Identifier: MIT OR Apache-2.0

//! Unit and property tests for `irontraffic_balancer::algo::p2c`.
//!
//! ALLOCATION FREEDOM, STATED ACCURATELY (see finding 1 of PR 875's review). This issue's
//! own text asks for a counting `#[global_allocator]` test. An earlier version of this doc
//! said that design "cannot compile here" because `GlobalAlloc` needs the one keyword this
//! workspace "denies everywhere with no exception". That is false, the same way it was false
//! in `crates/irontraffic-tls/tests/alloc_gate.rs` before issue #719 corrected it there: the
//! root `Cargo.toml` sets `unsafe_code = "deny"`, and `deny` is the OVERRIDABLE lint level;
//! `forbid` is the level that cannot be overridden, and this workspace does not use it for
//! `unsafe_code`. A counting `#[global_allocator]` behind
//! `#![allow(unsafe_code, reason = "...")]` was verified elsewhere in this workspace to
//! compile, run, and pass `cargo clippy --all-targets --all-features -- -D warnings`. What
//! actually blocks it HERE is `scripts/invariant-lints.sh` rule 15, `no-unsafe`, whose own
//! failure text grants no self-service exception: "There is no exception an implementer is
//! authorized to make; raise it on the issue instead." Whether to grant that exception for
//! `irontraffic-balancer`'s test files is the owner's call, and it is being raised separately
//! rather than decided here. The issue's own pre-emptive concern that a process-wide counter
//! "would in any case count allocations made by every other test in this binary, including
//! `proptest`" is also not a reason to skip the design: the issue's own quoted shape already
//! answers it with an `ARMED` flag that is set only around the calls under measurement.
//!
//! Pending that decision, `p2c_module_source_never_allocates` below is a SUBSTITUTE, not an
//! equivalent: a source-text scan over `src/algo/p2c.rs`, closely mirroring the call
//! spellings `scripts/invariant-lints.sh`'s `hot-path-allocation` rule already watches for on
//! every module carrying a `//! HOT PATH` marker, which this file's target does. State
//! plainly what that does and does not establish, because a clean run of a deny-list text
//! scan is not a proof of zero allocations: it catches an allocating call that appears,
//! textually, in the scanned file, and NOTHING ELSE. It cannot distinguish a function that
//! allocates zero times from one that allocates on every call through a spelling nobody
//! added to the list (a call taken by function pointer, `Type::method(receiver)`'s fully
//! qualified form instead of `receiver.method()`, or a call inside a dependency this file
//! merely invokes), and it fires on a listed call that appears in a comment or a string
//! literal exactly as readily as on one that runs. A clean run here means "none of the
//! listed calls appear, textually, in `src/algo/p2c.rs`", nothing more.

use std::cell::Cell;
use std::net::{Ipv4Addr, SocketAddr, SocketAddrV4};
use std::sync::OnceLock;
use std::sync::atomic::Ordering;

use irontraffic_balancer::{
    CostKind, MAX_EXCLUDE, pick_excluding, pick_least_request, pick_peak_ewma, sample_two,
};
use irontraffic_upstream::{
    CostCtx, EndpointAddr, EndpointId, EndpointIdentity, EndpointRegistry, EndpointStats, EwmaCfg,
};
use proptest::prelude::*;

// ---------------------------------------------------------------------------------------
// Fixtures
// ---------------------------------------------------------------------------------------

/// Number of endpoints the shared property-test fixture interns. Local indices generated by
/// the property tests below are drawn from `0..PROPTEST_N`, so every one is in range by
/// construction; slices may still be longer than this (up to 256), repeating local indices,
/// which is realistic and does not affect any property under test.
const PROPTEST_N: u32 = 64;

/// Builds a leaked registry (`Box::leak`, explicitly permitted by this issue for test
/// fixtures) with `n` freshly interned endpoints, plain `ids` and `weights` arrays, and an
/// identity `slice` covering all of them (`0..n`). Each call leaks its own independent
/// arena, per [`EndpointRegistry::install`]'s own contract, so unit tests never share state.
#[allow(
    clippy::expect_used,
    reason = "fixture helper reachable only from #[test] and proptest! bodies; a malformed \
              fixture must fail the calling test loudly rather than propagate a Result \
              through every test signature in this file"
)]
fn fixture(
    n: u32,
) -> (
    &'static EndpointRegistry,
    Vec<EndpointId>,
    Vec<u32>,
    Vec<u32>,
) {
    let (reg, mut writer) = EndpointRegistry::install(n.max(1))
        .expect("n.max(1) is nonzero and far under MAX_CAPACITY");
    let mut ids = Vec::with_capacity(n as usize);
    for i in 0..n {
        let identity = EndpointIdentity {
            addr: EndpointAddr::Socket(SocketAddr::V4(SocketAddrV4::new(
                Ipv4Addr::from(0x0A00_0000u32.wrapping_add(i)),
                80,
            ))),
            hostname: None,
        };
        let id = writer
            .intern(&identity)
            .expect("fixture registry is sized exactly for n distinct endpoints");
        ids.push(id);
    }
    let weights = vec![1u32; n as usize];
    let slice: Vec<u32> = (0..n).collect();
    (reg, ids, weights, slice)
}

/// Declares a once-built fixture of [`PROPTEST_N`] endpoints, so a property test with
/// hundreds of generated cases does not leak hundreds of registries.
///
/// ONE PER PROPERTY TEST, NOT SHARED. `cargo test` runs `#[test]` functions on separate
/// threads by default, and every property test that sets `inflight`/`cost` mutates the
/// registry's stats out of band from the ordinary call graph (`Ordering::Relaxed` stores on
/// shared atomics). A single fixture shared across property tests is consequently racy
/// across THEM, not merely across proptest's own cases within one: one test's write can
/// land between another's `set inflight` and its own read of the same slot, both on
/// different threads. That is not a memory-safety issue (atomics are always well-defined),
/// but it is a real, observed test-flakiness one: an earlier version of this file shared one
/// fixture and `p2c_picks_the_cheaper_of_the_two_sampled` failed intermittently, depending
/// on `cargo test`'s scheduling, with a value that could only have come from a different
/// property test's concurrent write. Each macro invocation below declares its own
/// independent `static`, so no two property tests ever share a mutable endpoint.
macro_rules! once_fixture {
    ($name:ident) => {
        fn $name() -> &'static (&'static EndpointRegistry, Vec<EndpointId>, Vec<u32>) {
            static FIXTURE: OnceLock<(&'static EndpointRegistry, Vec<EndpointId>, Vec<u32>)> =
                OnceLock::new();
            FIXTURE.get_or_init(|| {
                let (reg, ids, weights, _slice) = fixture(PROPTEST_N);
                (reg, ids, weights)
            })
        }
    };
}

once_fixture!(fixture_for_returns_in_range);
once_fixture!(fixture_for_cheaper_of_two);
once_fixture!(fixture_for_exclusion);
once_fixture!(fixture_for_work_bound);

fn default_ctx() -> CostCtx {
    CostCtx {
        now_ms: 1_000,
        decay_ms: 10_000,
        default_rtt_ms: 1_000.0,
        max_requests: u32::MAX,
    }
}

fn set_inflight(stats: &EndpointStats, v: u32) {
    stats.inflight.store(v, Ordering::Relaxed);
}

/// Seeds `stats`'s peak-EWMA estimate to exactly `rtt_ms` as of `now_ms`, by recording one
/// sample into a freshly zeroed word: `record_rtt`'s first call on a zero word packs the
/// clamped sample directly with no blending, so this is exact, not merely close.
fn set_rtt(stats: &EndpointStats, rtt_ms: f32, now_ms: u32) {
    let cfg = EwmaCfg {
        decay_ms: 10_000,
        default_rtt_ms: 1_000.0,
    };
    stats.record_rtt(rtt_ms, now_ms, &cfg);
}

/// `SplitMix64`: three lines, no dependency. Used by every test below that needs many
/// pseudorandom `u64` draws; test 3's own name calls out this exact generator, and reusing
/// one already-exercised implementation across the other draw-heavy tests is simpler than
/// writing several.
fn next_draw(state: &mut u64) -> u64 {
    *state = state.wrapping_add(0x9E37_79B9_7F4A_7C15);
    let mut z = *state;
    z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
    z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
    z ^ (z >> 31)
}

// ---------------------------------------------------------------------------------------
// sample_two
// ---------------------------------------------------------------------------------------

#[test]
fn sample_two_is_distinct_at_n_two() {
    for draw in [0u64, 1, u64::MAX, 0x1234_5678_9abc_def0] {
        let (a, b) = sample_two(draw, 2);
        assert_ne!(a, b, "draw {draw:#x} produced a duplicate pair");
        assert!(
            (a, b) == (0, 1) || (a, b) == (1, 0),
            "draw {draw:#x} produced an out-of-range pair ({a}, {b})"
        );
    }
}

#[test]
fn sample_two_extremes() {
    assert_eq!(sample_two(0, 8), (0, 1));
    assert_eq!(sample_two(u64::MAX, 8), (7, 6));
}

#[test]
fn sample_two_covers_the_range() {
    let mut rng: u64 = 0x9E37_79B9_7F4A_7C15;
    let mut counts = [0u32; 5];
    for _ in 0..100_000 {
        let draw = next_draw(&mut rng);
        let (a, _b) = sample_two(draw, 5);
        if let Some(c) = counts.get_mut(a as usize) {
            *c += 1;
        }
    }
    for (i, c) in counts.iter().enumerate() {
        assert!(
            *c >= 15_000,
            "index {i} appeared only {c} of 100000 times as `a`; want >= 15000 (25% of the \
             20000 expected under uniformity)"
        );
    }
}

// ---------------------------------------------------------------------------------------
// Pickers
// ---------------------------------------------------------------------------------------

#[test]
fn pick_empty_returns_none() {
    let (reg, ids, weights, _slice) = fixture(0);
    let cx = default_ctx();
    let result = pick_peak_ewma(&[], &ids, &weights, reg.stats_slice(), &cx, 42);
    assert_eq!(result, None);
}

#[test]
fn pick_single_returns_zero_without_reading_stats() {
    let (reg, ids, weights, slice) = fixture(1);
    let stats = reg.stats_slice();
    let st = stats
        .get(ids[0].0 as usize)
        .expect("the one interned endpoint has a stats line");
    set_inflight(st, u32::MAX - 1);
    let cx = CostCtx {
        max_requests: 1,
        ..default_ctx()
    };
    let result = pick_peak_ewma(&slice, &ids, &weights, stats, &cx, 999);
    assert_eq!(
        result,
        Some(0),
        "u == 1 must return Some(0) even though inflight (u32::MAX - 1) is far past \
         max_requests (1), because no statistic is read at all"
    );
}

#[test]
fn pick_two_is_exact() {
    let (reg, ids, weights, slice) = fixture(2);
    let stats = reg.stats_slice();
    set_inflight(stats.get(ids[0].0 as usize).expect("stats"), 5);
    set_inflight(stats.get(ids[1].0 as usize).expect("stats"), 3);
    let cx = default_ctx();
    for draw in 0..64u64 {
        let result = pick_least_request(&slice, &ids, &weights, stats, &cx, draw);
        assert_eq!(
            result,
            Some(1),
            "draw {draw}: u == 2 must always pick the lower-inflight endpoint, never sample"
        );
    }

    // The loop above does not prove the exact-compare branch ran: at u == 2, sampling
    // without replacement also returns both indices, so better_of would still compare
    // both exhaustively and return the same Some(1) for every draw regardless of which
    // branch produced the pair. Only a TIE distinguishes them. The exact-compare branch
    // calls `better_of(0, 1)` directly, so a tie always resolves to Some(0) (edge case 5:
    // "ties go to a, the first sampled index", and index 0 is always `a` here because
    // there is no sampling to reorder it). A mutant that fell through to
    // `sample_two(draw, 2)` instead would resolve the same tie to whichever of {0, 1}
    // `sample_two` drew as `a` for that particular draw, which varies with the draw.
    // Found by mutation: deleting pick_with's entire `n == 2` branch survived every
    // assertion above.
    set_inflight(stats.get(ids[0].0 as usize).expect("stats"), 7);
    set_inflight(stats.get(ids[1].0 as usize).expect("stats"), 7);
    let mut rng = 0x7A17_D1FF_5CA1_ED00u64;
    for _ in 0..1_000 {
        let draw = next_draw(&mut rng);
        let result = pick_least_request(&slice, &ids, &weights, stats, &cx, draw);
        assert_eq!(
            result,
            Some(0),
            "draw {draw:#x}: u == 2 with tied costs must deterministically return \
             Some(0), the exact-compare branch's fixed tie winner; a result that varies \
             with the draw would mean the pick fell through to sample_two instead"
        );
    }
}

#[test]
fn pick_prefers_lower_inflight() {
    let (reg, ids, weights, slice) = fixture(8);
    let stats = reg.stats_slice();
    for &id in &ids {
        set_inflight(stats.get(id.0 as usize).expect("stats"), 100);
    }
    set_inflight(stats.get(ids[0].0 as usize).expect("stats"), 0);
    let cx = default_ctx();
    let mut rng = 0xD1B5_4A32_D192_ED03u64;
    let mut chosen_zero = 0u32;
    for _ in 0..10_000 {
        let draw = next_draw(&mut rng);
        if pick_least_request(&slice, &ids, &weights, stats, &cx, draw) == Some(0) {
            chosen_zero += 1;
        }
    }
    assert!(
        chosen_zero > 2_000,
        "endpoint 0 (inflight 0 of 8, all others at 100) chosen only {chosen_zero} of 10000 \
         times; want > 2000 (sampled with probability 2/8 and always wins when sampled)"
    );
}

#[test]
fn pick_peak_ewma_prefers_lower_rtt() {
    let (reg, ids, weights, slice) = fixture(4);
    let stats = reg.stats_slice();
    let now_ms = 1_000u32;
    let rtts = [10.0f32, 20.0, 30.0, 40.0];
    for (i, &id) in ids.iter().enumerate() {
        let st = stats.get(id.0 as usize).expect("stats");
        set_inflight(st, 1);
        let rtt = *rtts.get(i).expect("exactly 4 endpoints and 4 rtts");
        set_rtt(st, rtt, now_ms);
    }
    let cx = CostCtx {
        now_ms,
        ..default_ctx()
    };
    let mut counts = [0u32; 4];
    let mut rng = 0xA5A5_5A5A_1234_5678u64;
    for _ in 0..10_000 {
        let draw = next_draw(&mut rng);
        if let Some(i) = pick_peak_ewma(&slice, &ids, &weights, stats, &cx, draw)
            && let Some(c) = counts.get_mut(i as usize)
        {
            *c += 1;
        }
    }
    assert!(
        counts[0] > counts[1],
        "endpoint 0 (10 ms) should be chosen more than endpoint 1 (20 ms): {counts:?}"
    );
    assert!(
        counts[1] > counts[2],
        "endpoint 1 (20 ms) should be chosen more than endpoint 2 (30 ms): {counts:?}"
    );
    assert!(
        counts[2] > counts[3],
        "endpoint 2 (30 ms) should be chosen more than endpoint 3 (40 ms): {counts:?}"
    );
}

#[test]
fn pick_respects_weight() {
    let (reg, ids, weights, slice) = fixture(2);
    let mut weights = weights;
    if let Some(w) = weights.get_mut(1) {
        *w = 4;
    }
    let stats = reg.stats_slice();
    let cx = default_ctx();
    for draw in 0..64u64 {
        let result = pick_least_request(&slice, &ids, &weights, stats, &cx, draw);
        assert_eq!(
            result,
            Some(1),
            "draw {draw}: identical stats, weights 1 and 4; dividing by the larger weight \
             yields the smaller key, so index 1 must always win"
        );
    }
}

#[test]
fn pick_never_returns_out_of_range() {
    let mut rng = 0x0BAD_F00D_DEAD_BEEFu64;
    for &u in &[1u32, 2, 3, 7, 64] {
        let (reg, ids, weights, slice) = fixture(u);
        let stats = reg.stats_slice();
        let cx = default_ctx();
        for _ in 0..1_000 {
            let draw = next_draw(&mut rng);
            match pick_peak_ewma(&slice, &ids, &weights, stats, &cx, draw) {
                Some(i) => assert!(
                    (i as usize) < u as usize,
                    "u = {u}, draw {draw:#x}: returned out-of-range index {i}"
                ),
                None => panic!("u = {u}, draw {draw:#x}: unexpectedly returned None"),
            }
        }
    }
}

#[test]
fn pick_ignores_max_requests_saturated_pair_gracefully() {
    let (reg, ids, weights, slice) = fixture(4);
    let stats = reg.stats_slice();
    let max_requests = 10u32;
    for &id in &ids {
        set_inflight(stats.get(id.0 as usize).expect("stats"), max_requests);
    }
    let cx = CostCtx {
        max_requests,
        ..default_ctx()
    };
    for draw in 0..64u64 {
        let result = pick_least_request(&slice, &ids, &weights, stats, &cx, draw);
        assert!(
            result.is_some(),
            "draw {draw}: every endpoint saturated at max_requests must still select \
             something, not None; None means an empty slice, never an overloaded one"
        );
    }
}

#[test]
fn pick_prefers_the_resolvable_candidate_when_one_local_index_is_out_of_range() {
    // Edge case 8: an out-of-range local index in `slice` (a corrupt snapshot). `key()`
    // returns `None` for that candidate; `better_of` must prefer whichever candidate's
    // key resolves, in EITHER position, and return `None` only when both are
    // unresolvable. Untested before this: every slice elsewhere in this file (including
    // every property-test generator) holds only in-range local indices, so the two
    // single-`None` arms of `better_of`'s match were never exercised, and swapping them
    // (so the picker returns the UNRESOLVABLE candidate instead) survived the whole
    // suite.
    let (reg, ids, weights, _all) = fixture(3);
    let stats = reg.stats_slice();
    let cx = default_ctx();
    let out_of_range = u32::try_from(weights.len()).expect("3 fits in u32"); // past every valid local index

    // Unresolvable candidate first (slice index 0): the resolvable sibling at slice
    // index 1 must win.
    let slice_a = vec![out_of_range, 1];
    for draw in 0..64u64 {
        let result = pick_least_request(&slice_a, &ids, &weights, stats, &cx, draw);
        assert_eq!(
            result,
            Some(1),
            "draw {draw}: slice index 0 names an out-of-range local index; the \
             resolvable sibling at slice index 1 must win, never the unresolvable one"
        );
    }

    // Unresolvable candidate second (slice index 1): the resolvable sibling at slice
    // index 0 must win.
    let slice_b = vec![1u32, out_of_range];
    for draw in 0..64u64 {
        let result = pick_least_request(&slice_b, &ids, &weights, stats, &cx, draw);
        assert_eq!(
            result,
            Some(0),
            "draw {draw}: slice index 1 names an out-of-range local index; the \
             resolvable sibling at slice index 0 must win, never the unresolvable one"
        );
    }

    // Both unresolvable: neither candidate can be resolved, so the picker must return
    // None rather than an index whose local value cannot be resolved.
    let slice_c = vec![out_of_range, out_of_range + 1];
    for draw in 0..64u64 {
        let result = pick_least_request(&slice_c, &ids, &weights, stats, &cx, draw);
        assert_eq!(
            result, None,
            "draw {draw}: both candidates are out of range; the picker must return None"
        );
    }
}

// ---------------------------------------------------------------------------------------
// Exclusion
// ---------------------------------------------------------------------------------------

#[test]
fn pick_excluding_avoids_excluded_local_index() {
    // Local indices 10..13 need a registry sized past 13, even though only 4 of its
    // endpoints are ever referenced by `slice`.
    let (reg, ids, weights, _all) = fixture(14);
    let stats = reg.stats_slice();
    let slice = vec![10u32, 11, 12, 13];
    let exclude = vec![10u32];
    let cx = default_ctx();
    let mut rng = 0x1357_9BDF_2468_ACE0u64;
    for _ in 0..1_000 {
        let draw = next_draw(&mut rng);
        let result = pick_excluding(
            CostKind::LeastRequest,
            &slice,
            &ids,
            &weights,
            stats,
            &cx,
            draw,
            &exclude,
        );
        if let Some(i) = result {
            let local = *slice.get(i as usize).expect("I1: result is in range");
            assert_ne!(
                local, 10,
                "draw {draw:#x}: returned excluded local index 10"
            );
        }
    }
}

#[test]
fn pick_excluding_all_returns_none() {
    // The issue's own prose says "exclude covers all four local indices", but
    // MAX_EXCLUDE == 3 makes an exclude list of length 4 hit the OVERSIZED-list
    // rejection (edge case 9) rather than the EVERY-ENTRY-EXCLUDED path (edge case 11)
    // this test's name is about; those are two different `pick_excluding` code paths
    // with two different justifications. u == 3 is the only slice length at which
    // "exclude covers every entry" is expressible within the MAX_EXCLUDE == 3 budget,
    // so this test uses u == 3. See this implementation's report for the exact
    // contradiction quoted from the issue text.
    let (reg, ids, weights, slice) = fixture(3);
    let stats = reg.stats_slice();
    let exclude = slice.clone();
    assert_eq!(exclude.len(), MAX_EXCLUDE);
    let cx = default_ctx();
    let mut rng = 0x2468_ACE0_1357_9BDFu64;
    for _ in 0..64 {
        let draw = next_draw(&mut rng);
        let result = pick_excluding(
            CostKind::LeastRequest,
            &slice,
            &ids,
            &weights,
            stats,
            &cx,
            draw,
            &exclude,
        );
        assert_eq!(
            result, None,
            "draw {draw:#x}: excluding every entry of the slice must return None"
        );
    }
}

#[test]
fn pick_excluding_falls_back_deterministically() {
    let (reg, ids, weights, _all) = fixture(13);
    let stats = reg.stats_slice();
    let slice = vec![10u32, 11, 12];
    let exclude = vec![10u32, 11];
    let cx = default_ctx();
    let mut rng = 0x0F0F_0F0F_F0F0_F0F0u64;
    for _ in 0..1_000 {
        let draw = next_draw(&mut rng);
        let result = pick_excluding(
            CostKind::LeastRequest,
            &slice,
            &ids,
            &weights,
            stats,
            &cx,
            draw,
            &exclude,
        );
        assert_eq!(
            result,
            Some(2),
            "draw {draw:#x}: the only non-excluded slice entry is index 2 (local 12); the \
             fallback scan must find it whenever the three bounded resamples do not"
        );
    }
}

/// Pins the resample budget at EXACTLY three attempts, deterministically, rather than
/// relying on a property test's random luck to reach the branch this matters in. Builds 8
/// endpoints with distinct costs (`inflight` 0..=7, weight 1, so `load_key` is exactly
/// `inflight + 1`), excludes the three CHEAPEST (local indices 0, 1, 2), and brute-force
/// searches, using only this crate's public API, for a `draw` whose first three resample
/// attempts (rotations 0, 21, 42) all fail (each attempt's winner is one of the three
/// excluded, cheapest endpoints, since an excluded entry beats any non-excluded one it is
/// paired against) while a hypothetical FOURTH attempt (rotation 63) would succeed on a
/// non-excluded survivor that is not the true minimum. A `pick_excluding` correctly bounded
/// at three attempts falls through to the deterministic scan for such a draw and returns
/// the true minimum, local index 3; one that tried a fourth attempt would return whatever
/// that attempt happened to sample instead. Confirmed by injection: this test fails (a
/// wrong `Some` instead of `Some(3)`) against the same `0..3u32` to `0..200u32` mutation
/// property test `p2c_work_is_bounded_by_slice_length`'s own doc comment names, closing the
/// gap a random property test can only close probabilistically.
#[test]
fn pick_excluding_never_tries_a_fourth_resample() {
    let (reg, ids, weights, slice) = fixture(8);
    let stats = reg.stats_slice();
    for (i, &id) in ids.iter().enumerate() {
        let st = stats.get(id.0 as usize).expect("stats");
        let inflight = u32::try_from(i).expect("8 endpoints fits in u32");
        set_inflight(st, inflight);
    }
    let cx = default_ctx();
    // fixture(8)'s slice is exactly [0, 1, ..., 7], so slice index, local index, and
    // inflight all coincide here; `exclude` names local indices, which are the same values.
    let exclude = vec![0u32, 1, 2];
    let min_local = 3u32;

    let winner_of = |draw: u64, attempt: u32| -> u32 {
        let d = draw.rotate_left(attempt * 21);
        let (a, b) = sample_two(d, 8);
        let key = |i: u32| -> u32 {
            let local = *slice
                .get(i as usize)
                .expect("i < 8 by sample_two's own I-P1");
            let id = ids.get(local as usize).expect("in range");
            stats
                .get(id.0 as usize)
                .expect("in range")
                .load_key(1.0, &cx)
        };
        if key(b) < key(a) { b } else { a }
    };

    // Candidates come from SplitMix64, not a plain incrementing counter: `draw` and
    // `draw + 1` differ only in their low bits, so an incrementing search leaves the high
    // 32 bits (and therefore sample_two's second index before rotation) nearly constant
    // and starves the search of the diversity the probability estimate below assumes.
    let mut found = None;
    let mut rng = 0x5EED_1234_5678_9ABCu64;
    for _ in 0..2_000_000 {
        let draw = next_draw(&mut rng);
        let first_three_fail = (0..3u32).all(|attempt| exclude.contains(&winner_of(draw, attempt)));
        if !first_three_fail {
            continue;
        }
        let fourth = winner_of(draw, 3);
        if !exclude.contains(&fourth) && fourth != min_local {
            found = Some(draw);
            break;
        }
    }
    let draw = found.expect(
        "a distinguishing draw must exist well within 2000000 candidates: each attempt \
         fails with probability C(5,2)/C(8,2) roughly 64%, and a qualifying fourth attempt \
         is independently likely, so the combined event is common, not rare",
    );

    let result = pick_excluding(
        CostKind::LeastRequest,
        &slice,
        &ids,
        &weights,
        stats,
        &cx,
        draw,
        &exclude,
    );
    assert_eq!(
        result,
        Some(min_local),
        "draw {draw:#x} was constructed so the first three resample attempts fail and a \
         fourth would wrongly succeed on a non-minimal survivor; a correctly bounded \
         pick_excluding must fall through to the deterministic scan and return the true \
         minimum, local index {min_local}, never a fourth attempt's answer"
    );
}

/// Pins the resample budget at EXACTLY three attempts from BELOW, complementing the test
/// above's pin from above. Before this test, the only thing distinguishing "three
/// attempts" from "fewer than three" was `p2c_work_is_bounded_by_slice_length`'s replica,
/// which counts calls probabilistically: confirmed by injection, mutating the real
/// `0..3u32` attempt range to `0..1u32` was caught by that property test in some runs and
/// survived it in others, so the resample count's LOWER bound was pinned only
/// probabilistically.
///
/// Brute-force searches for a draw whose first TWO resample attempts (rotations 0 and 21)
/// both fail (each attempt's winner is one of the three excluded, cheapest endpoints)
/// while the THIRD attempt (rotation 42) succeeds on a non-excluded survivor that is not
/// the true minimum. A `pick_excluding` that tried only one or two attempts (`0..1u32` or
/// `0..2u32` in place of `0..3u32`) would never reach that third attempt's winner and
/// would instead fall through to the deterministic scan and return the true minimum,
/// local index 3, so this test fails deterministically against either mutation, the same
/// way `pick_excluding_never_tries_a_fourth_resample` above pins the upper bound.
#[test]
fn pick_excluding_uses_all_three_resamples() {
    let (reg, ids, weights, slice) = fixture(8);
    let stats = reg.stats_slice();
    for (i, &id) in ids.iter().enumerate() {
        let st = stats.get(id.0 as usize).expect("stats");
        let inflight = u32::try_from(i).expect("8 endpoints fits in u32");
        set_inflight(st, inflight);
    }
    let cx = default_ctx();
    // fixture(8)'s slice is exactly [0, 1, ..., 7], so slice index, local index, and
    // inflight all coincide here; `exclude` names local indices, which are the same
    // values.
    let exclude = vec![0u32, 1, 2];
    let min_local = 3u32;

    let winner_of = |draw: u64, attempt: u32| -> u32 {
        let d = draw.rotate_left(attempt * 21);
        let (a, b) = sample_two(d, 8);
        let key = |i: u32| -> u32 {
            let local = *slice
                .get(i as usize)
                .expect("i < 8 by sample_two's own I-P1");
            let id = ids.get(local as usize).expect("in range");
            stats
                .get(id.0 as usize)
                .expect("in range")
                .load_key(1.0, &cx)
        };
        if key(b) < key(a) { b } else { a }
    };

    let mut found = None;
    let mut rng = 0xB16B_00B5_C0DE_1234u64;
    for _ in 0..2_000_000 {
        let draw = next_draw(&mut rng);
        let first_two_fail = (0..2u32).all(|attempt| exclude.contains(&winner_of(draw, attempt)));
        if !first_two_fail {
            continue;
        }
        let third = winner_of(draw, 2);
        if !exclude.contains(&third) && third != min_local {
            found = Some((draw, third));
            break;
        }
    }
    let (draw, expected_third) = found.expect(
        "a distinguishing draw must exist well within 2000000 candidates, by the same \
         probability argument as pick_excluding_never_tries_a_fourth_resample",
    );

    let result = pick_excluding(
        CostKind::LeastRequest,
        &slice,
        &ids,
        &weights,
        stats,
        &cx,
        draw,
        &exclude,
    );
    assert_eq!(
        result,
        Some(expected_third),
        "draw {draw:#x} was constructed so the first two resample attempts fail and the \
         third succeeds on a non-minimal survivor (local index {expected_third}); a \
         pick_excluding that tried fewer than three attempts would fall through to the \
         deterministic scan instead and wrongly return the true minimum, local index \
         {min_local}"
    );
}

/// Pins the deterministic fallback scan to the GLOBAL MINIMUM among non-excluded entries,
/// not merely the first one the scan happens to visit. Found by mutation testing
/// (`cargo mutants -j 1 --file src/algo/p2c.rs`): replacing the scan's `k < bk` comparator
/// with `k == bk` or `k <= bk` survived every other test in this file, including the
/// fourth-resample test above, because that test's own search only controls which draws
/// make the three bounded resamples fail, not where the scan's start offset lands, and for
/// its particular draw the scan happens to visit the true minimum first anyway.
///
/// Reuses the same 8-distinct-cost, three-cheapest-excluded fixture, and searches for a
/// draw where the scan's start offset (`reduce(low_u32(draw), 8)`, reimplemented here from
/// the issue's own documented Lemire formula and low-bits split, since `reduce` and
/// `low_u32` are `pub(crate)`) lands on one of the non-minimal survivors (4, 5, 6, or 7)
/// rather than on the true minimum (3) or on 0, 1, or 2 (excluded, which the scan would
/// skip on its way to 3 regardless). For such a draw, "return the first non-excluded entry
/// visited" and "return the entry with the lowest key" disagree, so only a scan that
/// genuinely tracks the minimum returns local index 3 here.
#[test]
fn pick_excluding_scan_finds_the_minimum_not_the_first_hit() {
    let (reg, ids, weights, slice) = fixture(8);
    let stats = reg.stats_slice();
    for (i, &id) in ids.iter().enumerate() {
        let st = stats.get(id.0 as usize).expect("stats");
        let inflight = u32::try_from(i).expect("8 endpoints fits in u32");
        set_inflight(st, inflight);
    }
    let cx = default_ctx();
    let exclude = vec![0u32, 1, 2];
    let min_local = 3u32;

    let winner_of = |draw: u64, attempt: u32| -> u32 {
        let d = draw.rotate_left(attempt * 21);
        let (a, b) = sample_two(d, 8);
        let key = |i: u32| -> u32 {
            let local = *slice
                .get(i as usize)
                .expect("i < 8 by sample_two's own I-P1");
            let id = ids.get(local as usize).expect("in range");
            stats
                .get(id.0 as usize)
                .expect("in range")
                .load_key(1.0, &cx)
        };
        if key(b) < key(a) { b } else { a }
    };
    // Reimplements reduce's documented Lemire formula and low_u32's documented bit split,
    // purely to steer the search: both are part of this crate's stable, published algorithm
    // (see the module doc comment on `reduce`), not an implementation detail this test
    // reaches past its own contract to observe.
    let scan_start = |draw: u64| -> u32 {
        #[allow(
            clippy::cast_possible_truncation,
            reason = "reimplements low_u32's documented bit split for a test-only search \
                      key, not production code: intentionally takes the low 32 bits"
        )]
        let x = draw as u32;
        #[allow(
            clippy::cast_possible_truncation,
            reason = "reimplements reduce's documented Lemire formula for a test-only search \
                      key; product < 2^35 (a u32 times 8), so the shifted result is < 8, \
                      always fits in u32"
        )]
        let start = ((u64::from(x) * 8) >> 32) as u32;
        start
    };

    let mut found = None;
    let mut rng = 0xFACE_FEED_C0FF_EE00u64;
    for _ in 0..2_000_000 {
        let draw = next_draw(&mut rng);
        let all_three_fail = (0..3u32).all(|attempt| exclude.contains(&winner_of(draw, attempt)));
        if !all_three_fail {
            continue;
        }
        if scan_start(draw) >= 4 {
            found = Some(draw);
            break;
        }
    }
    let draw = found.expect(
        "a draw whose scan start lands past the minimum must exist well within 2000000 \
         candidates: P(all three resamples fail) is roughly 26% and P(scan start >= 4) is \
         50%, independent of it, so the combined event is common, not rare",
    );

    let result = pick_excluding(
        CostKind::LeastRequest,
        &slice,
        &ids,
        &weights,
        stats,
        &cx,
        draw,
        &exclude,
    );
    assert_eq!(
        result,
        Some(min_local),
        "draw {draw:#x}: the scan's start offset does not land on the minimum, so a scan \
         that stopped at the first non-excluded entry instead of tracking the lowest key \
         would return something other than local index {min_local} here"
    );
}

#[test]
fn pick_excluding_rejects_an_oversized_exclude_list() {
    let (reg, ids, weights, slice) = fixture(64);
    let stats = reg.stats_slice();
    let cx = default_ctx();
    let exclude: Vec<u32> = (0..64u32).collect();

    if cfg!(debug_assertions) {
        // A debug build's debug_assert fires before any key evaluation, which is a
        // stronger statement than "returns None": it never reaches the point where it
        // COULD have entered an O(u * r) loop. Caught with catch_unwind rather than
        // `#[should_panic]` so this stays one test whose two branches share the same
        // fixture and exclude list, instead of two nearly-identical tests.
        let outcome = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
            pick_excluding(
                CostKind::LeastRequest,
                &slice,
                &ids,
                &weights,
                stats,
                &cx,
                0,
                &exclude,
            )
        }));
        assert!(
            outcome.is_err(),
            "a debug build must debug_assert when exclude.len() > MAX_EXCLUDE"
        );
    } else {
        let result = pick_excluding(
            CostKind::LeastRequest,
            &slice,
            &ids,
            &weights,
            stats,
            &cx,
            0,
            &exclude,
        );
        assert_eq!(
            result, None,
            "a release build must return None for an oversized exclude list, not a value"
        );

        // "the point is that the function returns before entering any O(u * r) loop":
        // in release the debug_assert compiles out, so wall time as u grows from 64 to
        // 4096 is what is left to show the rejection did not scale with u.
        let (reg_big, ids_big, weights_big, slice_big) = fixture(4096);
        let stats_big = reg_big.stats_slice();
        let exclude_big: Vec<u32> = (0..4096u32).collect();

        let iterations = 20_000u32;
        let small_elapsed = {
            let start = std::time::Instant::now();
            for i in 0..iterations {
                let _ = pick_excluding(
                    CostKind::LeastRequest,
                    &slice,
                    &ids,
                    &weights,
                    stats,
                    &cx,
                    u64::from(i),
                    &exclude,
                );
            }
            start.elapsed()
        };
        let big_elapsed = {
            let start = std::time::Instant::now();
            for i in 0..iterations {
                let _ = pick_excluding(
                    CostKind::LeastRequest,
                    &slice_big,
                    &ids_big,
                    &weights_big,
                    stats_big,
                    &cx,
                    u64::from(i),
                    &exclude_big,
                );
            }
            start.elapsed()
        };
        assert!(
            big_elapsed <= small_elapsed.saturating_mul(20)
                || big_elapsed < std::time::Duration::from_millis(5),
            "u = 4096 took {big_elapsed:?} against u = 64's {small_elapsed:?}; an O(1) \
             rejection must not scale with u"
        );
    }
}

/// `CostKind::PeakEwma` reaching `pick_excluding`'s empty-exclude dispatch (line ~403).
/// Before this test, every `pick_excluding` call in this file and in `benches/pick.rs`
/// passed `CostKind::LeastRequest`, so `PeakEwma` was never once exercised through this
/// function and both of its dispatch arms survived mutation, including one that routes
/// `PeakEwma` to `pick_least_request` instead of `pick_peak_ewma`.
///
/// Builds `u == 2` so the empty-exclude delegate's `n == 2` path does an exact compare
/// for every draw (no sampling), and sets stats so `cost_key` (peak-EWMA) and `load_key`
/// (least-request) rank the two endpoints OPPOSITELY: index 0 has the lower inflight but
/// a far higher RTT, index 1 the reverse. `PeakEwma` must therefore return index 1 for
/// every draw; a dispatch that fell through to `pick_least_request` would return index 0
/// for every draw instead.
#[test]
fn pick_excluding_peak_ewma_empty_exclude_dispatches_to_peak_ewma() {
    let (reg, ids, weights, slice) = fixture(2);
    let stats = reg.stats_slice();
    let now_ms = 1_000u32;
    let st0 = stats.get(ids[0].0 as usize).expect("stats");
    set_inflight(st0, 0); // lowest inflight: load_key favors this one
    set_rtt(st0, 1000.0, now_ms); // far highest rtt: cost_key strongly disfavors this one
    let st1 = stats.get(ids[1].0 as usize).expect("stats");
    set_inflight(st1, 2); // higher inflight: load_key disfavors this one
    set_rtt(st1, 1.0, now_ms); // far lowest rtt: cost_key strongly favors this one
    let cx = CostCtx {
        now_ms,
        ..default_ctx()
    };
    for draw in 0..64u64 {
        let result = pick_excluding(
            CostKind::PeakEwma,
            &slice,
            &ids,
            &weights,
            stats,
            &cx,
            draw,
            &[],
        );
        assert_eq!(
            result,
            Some(1),
            "draw {draw}: the empty-exclude dispatch must call pick_peak_ewma for \
             CostKind::PeakEwma, not pick_least_request; index 1 has the far lower \
             peak-EWMA cost despite the higher inflight, so only the correct dispatch \
             returns it for every draw at u == 2's exact compare"
        );
    }
}

/// `CostKind::PeakEwma` reaching `pick_excluding`'s resample-and-scan `key_fn` closure
/// (line ~417), the other of the two dispatch points finding 3 named. Only reachable
/// with a non-empty `exclude`.
///
/// `u == 3`, local index 0 excluded and given costs that never win any comparison it is
/// part of (so it never confuses which of the other two "won" a resample attempt), and
/// local indices 1 and 2 set so `cost_key` (peak-EWMA) and `load_key` (least-request)
/// rank them OPPOSITELY: index 1 has the lower inflight but a far higher RTT, index 2
/// the reverse. Every one of the three possible sampled pairs from `{0, 1, 2}` produces
/// an immediate, non-excluded winner under the correct (`cost_key`) ordering (0 never
/// wins), so the result is fully determined by which pair `sample_two`'s first attempt
/// draws: `{0, 1}` (winner 1, roughly a third of draws) or `{0, 2}` / `{1, 2}` (winner 2,
/// roughly two thirds). A `key_fn` that ignored `kind` and always used `load_key`
/// instead would have index 0 win every pair it is part of and get excluded, so almost
/// every draw would fall through to the deterministic scan or resolve on the one
/// surviving pair, and in EITHER case would resolve on index 1 (the lower `load_key`),
/// never index 2: `counts[2]` would collapse from roughly two thirds to zero.
#[test]
fn pick_excluding_peak_ewma_resample_and_scan_use_peak_ewma_cost() {
    let (reg, ids, weights, slice) = fixture(3);
    let stats = reg.stats_slice();
    let now_ms = 1_000u32;
    let inflights = [0u32, 1, 2];
    let rtts = [1000.0f32, 50.0, 1.0];
    for (i, &id) in ids.iter().enumerate() {
        let st = stats.get(id.0 as usize).expect("stats");
        set_inflight(
            st,
            *inflights
                .get(i)
                .expect("exactly 3 endpoints and 3 inflights"),
        );
        set_rtt(
            st,
            *rtts.get(i).expect("exactly 3 endpoints and 3 rtts"),
            now_ms,
        );
    }
    let cx = CostCtx {
        now_ms,
        ..default_ctx()
    };
    let exclude = vec![0u32];
    let mut counts = [0u32; 3];
    let mut rng = 0x9E3F_7A5A_C057_1234u64;
    for _ in 0..10_000 {
        let draw = next_draw(&mut rng);
        if let Some(i) = pick_excluding(
            CostKind::PeakEwma,
            &slice,
            &ids,
            &weights,
            stats,
            &cx,
            draw,
            &exclude,
        ) {
            assert_ne!(i, 0, "draw {draw:#x}: returned excluded local index 0");
            if let Some(c) = counts.get_mut(i as usize) {
                *c += 1;
            }
        }
    }
    assert!(
        counts[2] > 5_000,
        "the resample/scan key_fn must prefer index 2 (peak-EWMA cost far below index \
         1's) on roughly two thirds of draws; got {counts:?}. A key_fn that fell back to \
         load_key for PeakEwma (index 2 has the WORST load_key of the two non-excluded \
         candidates) would collapse this to near zero."
    );
}

// ---------------------------------------------------------------------------------------
// Property tests
// ---------------------------------------------------------------------------------------

proptest! {
    /// I-P1, and "the Envoy defect expressed as an assertion": for every draw and every
    /// n >= 2, sample_two returns two distinct, in-range indices.
    #[test]
    fn p2c_sample_two_always_distinct(n in 2u32..=100_000u32, draw: u64) {
        let (a, b) = sample_two(draw, n);
        prop_assert_ne!(a, b);
        prop_assert!(a < n);
        prop_assert!(b < n);
    }

    /// I1: every Some(i) a picker returns satisfies i < slice.len(), and a non-empty slice
    /// of in-range local indices never returns None.
    #[test]
    fn p2c_returns_in_range(
        slice in proptest::collection::vec(0u32..PROPTEST_N, 0..=256),
        inflights in proptest::collection::vec(any::<u32>(), PROPTEST_N as usize),
        costs in proptest::collection::vec(any::<u64>(), PROPTEST_N as usize),
        draw: u64,
    ) {
        let (reg, ids, weights) = fixture_for_returns_in_range();
        let stats = reg.stats_slice();
        for (i, &id) in ids.iter().enumerate() {
            if let Some(st) = stats.get(id.0 as usize) {
                if let Some(&inflight) = inflights.get(i) {
                    st.inflight.store(inflight, Ordering::Relaxed);
                }
                if let Some(&cost) = costs.get(i) {
                    st.cost.store(cost, Ordering::Relaxed);
                }
            }
        }
        let cx = default_ctx();
        let result = pick_peak_ewma(&slice, ids, weights, stats, &cx, draw);
        match result {
            Some(i) => prop_assert!((i as usize) < slice.len()),
            None => prop_assert!(
                slice.is_empty(),
                "a non-empty slice of in-range local indices returned None"
            ),
        }
    }

    /// Pins the comparator, including the tie rule: the returned index is always whichever
    /// of the two sampled candidates has the smaller key, ties going to the first.
    #[test]
    fn p2c_picks_the_cheaper_of_the_two_sampled(
        n in 3u32..=PROPTEST_N,
        draw: u64,
        inflights in proptest::collection::vec(any::<u32>(), PROPTEST_N as usize),
    ) {
        let (reg, ids, weights) = fixture_for_cheaper_of_two();
        let stats = reg.stats_slice();
        for (i, &id) in ids.iter().enumerate() {
            if let (Some(st), Some(&inflight)) = (stats.get(id.0 as usize), inflights.get(i)) {
                st.inflight.store(inflight, Ordering::Relaxed);
            }
        }
        let slice: Vec<u32> = (0..n).collect();
        let cx = default_ctx();
        let (a, b) = sample_two(draw, n);

        let key = |i: u32| -> Option<u32> {
            let local = *slice.get(i as usize)?;
            let w = *weights.get(local as usize)?;
            let id = ids.get(local as usize)?;
            let st = stats.get(id.0 as usize)?;
            #[allow(
                clippy::cast_precision_loss,
                reason = "test fixture weight is always 1, far below any precision-losing \
                          magnitude; matches the crate's own identical allow"
            )]
            let w_eff = w as f32;
            Some(st.load_key(w_eff, &cx))
        };
        let expected = match (key(a), key(b)) {
            (Some(ka), Some(kb)) => Some(if kb < ka { b } else { a }),
            (Some(_), None) => Some(a),
            (None, Some(_)) => Some(b),
            (None, None) => None,
        };

        let actual = pick_least_request(&slice, ids, weights, stats, &cx, draw);
        prop_assert_eq!(actual, expected);
    }

    /// I-P3: the returned local index is never in `exclude`, and `None` is returned only
    /// when every entry of the slice is excluded (or the slice is empty).
    #[test]
    fn p2c_exclusion_is_respected(
        slice in proptest::collection::vec(0u32..PROPTEST_N, 0..=64),
        exclude in proptest::collection::vec(0u32..PROPTEST_N, 0..=MAX_EXCLUDE),
        draw: u64,
    ) {
        let (reg, ids, weights) = fixture_for_exclusion();
        let stats = reg.stats_slice();
        let cx = default_ctx();
        let result = pick_excluding(
            CostKind::LeastRequest, &slice, ids, weights, stats, &cx, draw, &exclude,
        );
        if let Some(i) = result {
            let local = *slice.get(i as usize).expect("I1: result is in range");
            prop_assert!(!exclude.contains(&local));
        } else {
            let all_excluded =
                slice.is_empty() || slice.iter().all(|local| exclude.contains(local));
            prop_assert!(
                all_excluded,
                "returned None but the slice was non-empty and not fully excluded"
            );
        }
    }

    /// The assertion form of "no input makes the pick do more than one scan". Mirrors
    /// pick_excluding's own documented control flow using only this crate's public API
    /// (sample_two and EndpointStats::load_key), counting real load_key evaluations as it
    /// goes, and asserts the total never exceeds slice.len() + 6: six for the three bounded
    /// resamples (two candidates evaluated per attempt, unconditionally), and one per
    /// non-excluded entry for the single deterministic scan.
    ///
    /// WHY A REPLICA RATHER THAN INTERCEPTING pick_excluding's OWN INTERNAL CALLS. `reduce`,
    /// which the real fallback scan uses to pick its start offset, is `pub(crate)`, not
    /// exported, and this is an external integration test; there is also no seam in this
    /// crate's frozen public API (`stats: &[EndpointStats]`, a concrete type) through which
    /// a test could substitute a counting wrapper for the real one. This replica calls the
    /// SAME public primitives pick_excluding's own body calls, in the same documented order.
    ///
    /// THE COUNT BOUND ALONE IS NOT ENOUGH, AND IS NOT EVEN A CLAIM ABOUT THE REAL FUNCTION.
    /// `calls.get() <= n + 6` below is a property of THIS REPLICA's own control flow (at most
    /// three attempts times two keys, plus one pass over the slice), true by construction of
    /// the replica regardless of what `pick_excluding` itself does: a replica that always
    /// assumes exactly three attempts cannot, by counting its own calls, notice
    /// `pick_excluding` itself trying four, or forty, or none. It is kept only as a sanity
    /// check on the replica's OWN shape, so that a future edit to this test that accidentally
    /// turns the replica's resample loop into a retry-until-success loop is caught here
    /// rather than relying on `prop_assert_eq!` below to happen to find a disagreeing input.
    /// Confirmed by injection: mutating the real `0..3u32` attempt range to `0..200u32` left
    /// an earlier version of this test, which only compared call counts, at 21 of 21 passing.
    ///
    /// THE ENTIRE LOAD-BEARING CHECK IS `prop_assert_eq!(real, replica)` BELOW. The replica
    /// computes ITS OWN chosen index using the identical rotation formula, comparator, AND
    /// fallback-scan start offset as the real function's documented step 10 (reimplementing
    /// `reduce` and `low_u32`, both `pub(crate)`, exactly as
    /// `pick_excluding_scan_finds_the_minimum_not_the_first_hit` already does, rather than
    /// starting the scan at slice index 0 the way an earlier version of this replica did: that
    /// version's oracle disagreed with the real function, intermittently, whenever the
    /// non-excluded minimum was attained at more than one slice position, a duplicate local
    /// index the generator makes common once `slice.len() > PROPTEST_N`, because both sides
    /// break ties with a strict `<` and a different start offset visits a tied minimum in a
    /// different order; see the sibling test's own doc comment for a concrete replay of that
    /// disagreement). With the offsets aligned, real and replica visit the slice in the same
    /// order and so agree even on a duplicate-local-index tie, and a resample count, rotation
    /// formula, or scan offset that drifted from the documented design is very likely to
    /// select a different winner for some generated case and fail this assertion: re-running
    /// the same `0..200u32` injection against this version of the test fails it within the
    /// first handful of generated cases, and so does `let start = 0usize;` in place of
    /// production's `reduce(low_u32(draw), n_u32)`.
    #[test]
    fn p2c_work_is_bounded_by_slice_length(
        slice in proptest::collection::vec(0u32..PROPTEST_N, 0..=256),
        exclude in proptest::collection::vec(0u32..PROPTEST_N, 0..=8),
        inflights in proptest::collection::vec(any::<u32>(), PROPTEST_N as usize),
        draw: u64,
    ) {
        let (reg, ids, weights) = fixture_for_work_bound();
        let stats = reg.stats_slice();
        for (i, &id) in ids.iter().enumerate() {
            if let (Some(st), Some(&inflight)) = (stats.get(id.0 as usize), inflights.get(i)) {
                st.inflight.store(inflight, Ordering::Relaxed);
            }
        }
        let cx = default_ctx();
        let n = slice.len();

        let calls = Cell::new(0usize);
        let key = |i: u32| -> Option<u32> {
            let local = *slice.get(i as usize)?;
            let w = *weights.get(local as usize)?;
            let id = ids.get(local as usize)?;
            let st = stats.get(id.0 as usize)?;
            calls.set(calls.get() + 1);
            #[allow(
                clippy::cast_precision_loss,
                reason = "test fixture weight is always 1, far below any precision-losing \
                          magnitude; matches the crate's own identical allow"
            )]
            let w_eff = w as f32;
            Some(st.load_key(w_eff, &cx))
        };
        let better_of = |a: u32, b: u32| -> Option<u32> {
            match (key(a), key(b)) {
                (Some(ka), Some(kb)) => Some(if kb < ka { b } else { a }),
                (Some(_), None) => Some(a),
                (None, Some(_)) => Some(b),
                (None, None) => None,
            }
        };

        let replica: Option<u32> = if n == 0 || exclude.len() > MAX_EXCLUDE {
            None
        } else if exclude.is_empty() {
            if n == 1 {
                Some(0)
            } else if n == 2 {
                better_of(0, 1)
            } else {
                let (a, b) = sample_two(draw, u32::try_from(n).unwrap_or(u32::MAX));
                better_of(a, b)
            }
        } else if n == 1 {
            slice
                .first()
                .and_then(|&local| (!exclude.contains(&local)).then_some(0))
        } else {
            let n_u32 = u32::try_from(n).unwrap_or(u32::MAX);
            let mut found = None;
            for attempt in 0..3u32 {
                let d = draw.rotate_left(attempt * 21);
                let (a, b) = sample_two(d, n_u32);
                let Some(cand) = better_of(a, b) else {
                    break;
                };
                if let Some(&local) = slice.get(cand as usize)
                    && !exclude.contains(&local)
                {
                    found = Some(cand);
                    break;
                }
            }
            found.or_else(|| {
                // Reimplements reduce's documented Lemire formula and low_u32's documented
                // bit split (both `pub(crate)`, unreachable from this external integration
                // test) purely to align this replica's scan ORDER with production's step 10,
                // exactly as `pick_excluding_scan_finds_the_minimum_not_the_first_hit`
                // already does. Starting at slice index 0 here, as an earlier version of this
                // replica did, disagreed with the real function whenever the non-excluded
                // minimum was attained at more than one slice position: see this test's own
                // doc comment above.
                #[allow(
                    clippy::cast_possible_truncation,
                    reason = "reimplements low_u32's documented bit split for a test-only \
                              search key, not production code: intentionally takes the low \
                              32 bits"
                )]
                let x = draw as u32;
                #[allow(
                    clippy::cast_possible_truncation,
                    reason = "reimplements reduce's documented Lemire formula for a \
                              test-only search key; product < 2^64 (two u32 values \
                              multiplied), so the shifted result is provably < 2^32"
                )]
                let start = ((u64::from(x) * u64::from(n_u32)) >> 32) as u32 as usize;
                let mut best: Option<(u32, u32)> = None;
                for step in 0..n {
                    let i = (start + step) % n;
                    let Some(&local) = slice.get(i) else { continue };
                    if exclude.contains(&local) {
                        continue;
                    }
                    let i_u32 =
                        u32::try_from(i).expect("slice length bounded well under u32::MAX");
                    let Some(k) = key(i_u32) else { continue };
                    if best.is_none_or(|(_, bk)| k < bk) {
                        best = Some((i_u32, k));
                    }
                }
                best.map(|(i, _)| i)
            })
        };

        prop_assert!(
            calls.get() <= n + 6,
            "replica evaluated {} keys for n = {n}, exceeding the n + 6 bound (this bound \
             holds for the REPLICA by construction, not for pick_excluding itself: see this \
             test's own doc comment)",
            calls.get()
        );

        // An oversized exclude list debug_asserts inside pick_excluding itself (test 15's
        // own contract), so this cross-check only calls the real function when that
        // precondition holds; the oversized case is already covered by test 15.
        if exclude.len() <= MAX_EXCLUDE {
            let real = pick_excluding(
                CostKind::LeastRequest, &slice, ids, weights, stats, &cx, draw, &exclude,
            );
            prop_assert_eq!(real, replica);
        }
    }
}

// ---------------------------------------------------------------------------------------
// Allocation freedom (see the module doc comment on why this is a text scan)
// ---------------------------------------------------------------------------------------

/// Call spellings that can allocate, CLOSELY mirroring (not exactly duplicating) the shape
/// `scripts/invariant-lints.sh`'s `hot-path-allocation` rule already watches `src/algo/p2c.rs`
/// for on every pull request (it is marked `//! HOT PATH`); duplicated here as a Rust test so
/// this acceptance criterion has its own assertion inside `cargo test`, not only a shell gate.
///
/// PROVEN WEAKER THAN THE SHELL RULE ONCE, AND WIDENED IN RESPONSE (finding 1, PR 875's
/// review). An earlier version of this list let a real per-request heap allocation in
/// `excluded()`'s O(u) fallback-scan path through as `exclude.iter().copied().collect::<
/// Vec<u32>>()`: the shell rule's `\.collect(::<|\(\))` alternative catches the turbofish
/// form, but this list's plain `".collect("` substring is not a substring of
/// `".collect::<Vec<u32>>("` (the text between `collect` and `(` is `::<Vec<u32>>`, not
/// nothing), so it missed it, and the same injection also showed `parts.join(",")`,
/// `HashMap::with_capacity(8)`, `Vec::<u32>::new()`, and `VecDeque::with_capacity(4)` all
/// passing clean. `".collect::<"`, `".join("`, the bare `"::with_capacity("` (replacing the
/// two type-specific entries this list used to carry, since the shell rule's form is
/// generic over the receiver type), the bare `"::<"` (closing the turbofish-constructor gap
/// generically rather than enumerating every collection type's own turbofish spelling), and
/// `".into_boxed_slice("` / `".into_boxed_str("` below close every one of those five, and were
/// re-verified against the same five injected lines after widening.
///
/// STILL A TEXT SCAN, STILL NOT A PROOF: this closes the specific gap proven by injection,
/// not every gap shaped like it. It still cannot see a call taken by function pointer, or
/// the fully qualified `Type::method(receiver)` form in place of `receiver.method()` (the
/// shell rule's own doc comment names two real instances of that evasion elsewhere in this
/// workspace), and it fires just as readily on a listed spelling inside a comment or a
/// string literal as on one that runs.
const ALLOCATING_CALLS: [&str; 34] = [
    "format!(",
    ".to_string()",
    ".to_owned()",
    ".into_owned()",
    ".to_vec()",
    "vec![",
    "Vec::new(",
    "String::new(",
    "::with_capacity(",
    "::<",
    "HashMap::new(",
    "HashSet::new(",
    "BTreeMap::new(",
    "BTreeSet::new(",
    "VecDeque::new(",
    "BinaryHeap::new(",
    "LinkedList::new(",
    "String::from(",
    "Vec::from(",
    "Box::from(",
    "Box::new(",
    "Arc::new(",
    "Rc::new(",
    "Box::pin(",
    ".collect(",
    ".collect::<",
    ".join(",
    ".into_boxed_slice(",
    ".into_boxed_str(",
    ".clone()",
    ".to_lowercase()",
    ".to_uppercase()",
    ".push_str(",
    ".repeat(",
];

#[test]
fn p2c_module_source_never_allocates() {
    let source = include_str!("../src/algo/p2c.rs");
    for call in ALLOCATING_CALLS {
        assert!(
            !source.contains(call),
            "src/algo/p2c.rs contains `{call}`, which can allocate; this module is marked \
             //! HOT PATH and every function in it must stay allocation-free"
        );
    }
}
